#!/usr/bin/env ruby
# SPDX-License-Identifier: MIT

module Polispec
  module AgentsRender
    BODY_PATH = ".agents/directives/envs.md"
    AGENTS_FILE = "AGENTS.md"
    POLICY_PATH = "specs/polispec/policy.yml"
    ENV_NAMES = %w[dev test prod].freeze
    ROW_PATTERN = /\A\[[A-Z0-9]+\] /.freeze
    Rendered = Struct.new(:row, :body, :project)
    Source = Struct.new(:policy, :environments, :project)

    module_function

    def source_from_worktree(root, policy_path = POLICY_PATH)
      policy_file = File.join(File.expand_path(root), policy_path)
      env_file = File.join(File.dirname(policy_file), Environments::FILE)
      raise Polispec::Error, "#{policy_file} is missing" unless File.file?(policy_file)
      raise Polispec::Error, "#{env_file} is missing" unless File.file?(env_file)

      build_source(File.read(policy_file), File.read(env_file), policy_file, env_file)
    rescue SystemCallError => e
      raise Polispec::Error, e.message
    end

    def source_from_ref(repo, ref, policy_path = POLICY_PATH)
      env_path = Environments.path_for(policy_path)
      policy_text = Environments.git(File.expand_path(repo), "show", "#{ref}:#{policy_path}")
      env_text = Environments.git(File.expand_path(repo), "show", "#{ref}:#{env_path}")
      raise Polispec::Error, "#{ref}:#{policy_path} is missing" if policy_text.nil?
      raise Polispec::Error, "#{ref}:#{env_path} is missing" if env_text.nil?

      build_source(policy_text, env_text, "#{ref}:#{policy_path}", "#{ref}:#{env_path}")
    end

    def build_source(policy_text, env_text, policy_label, env_label)
      combined = Environments.combine(policy_text, env_text, policy_label)
      if combined.errors
        first = combined.errors.first
        label = first["pointer"].to_s.start_with?("/#{Environments::FILE}") ? env_label : policy_label
        raise Polispec::Error, "#{label} is invalid: #{Environments.first_message(combined.errors)}"
      end

      Source.new(combined.data, Schema::Document.parse(env_text, env_label), combined.data["project"])
    end

    def render(source)
      Rendered.new(row(source.environments), body(source), source.project)
    end

    def row(environments)
      envs = environments["environments"]
      "[ENVS] when developing this repo: it serves real users; dev is `#{envs['dev']['branch']}`, test is `#{envs['test']['branch']}`, prod is `#{envs['prod']['branch']}`; run `polispec resolve .` before writing and obey its verdict; table in #{BODY_PATH}   d/ENVS   ⚙ guard:polispec   ⚡ [always]"
    end

    def body(source)
      sections = [heading(source), table(source.environments), forbids(source.policy), promotion(source.policy), operators(source.environments), data(source.environments)]
      "#{sections.join("\n")}\n"
    end

    def heading(source)
      "# ENVS: #{source.project} environments\n\nGenerated by `polispec agents render` from specs/polispec/environments.yml and specs/polispec/policy.yml. Edit those files, never this one.\n"
    end

    def cell(value)
      text = value.is_a?(Array) ? value.join(", ") : value.to_s
      text.empty? ? "-" : text.gsub("|", "\\|")
    end

    def table(environments)
      lines = ["## Environments", "", "| Env | Tier | Branch | Checkout | Audience | Exposure | URL | Ports | Data classes |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
      ENV_NAMES.each do |name|
        spec = environments["environments"][name]
        cells = [name, spec["tier"], spec["branch"], spec["checkout"], spec["audience"], spec["exposure"], spec["url"], spec["ports"], spec["data_classes"]]
        lines << "| #{cells.map { |value| cell(value) }.join(' | ')} |"
      end
      "#{lines.join("\n")}\n"
    end

    def forbids(policy)
      lines = ["## What each environment forbids", ""]
      ENV_NAMES.each do |name|
        lines << "### #{name}"
        lines << ""
        rules = Array(policy["rules"]).select { |rule| applies?(rule, name) }
        rules.each { |rule| lines << rule_line(rule) }
        lines << "" unless rules.empty?
      end
      "#{lines.join("\n").rstrip}\n"
    end

    def applies?(rule, env)
      match = rule["match"] || {}
      return false if rule["verdict"] == "allow" && match["class"].nil?

      match["env"].nil? || match["env"] == env
    end

    def rule_line(rule)
      classes = Array((rule["match"] || {})["class"])
      "- #{rule['verdict']} #{rule['id']}: #{classes.empty? ? 'any action' : classes.join(', ')} — #{rule['reason'] || '-'}"
    end

    def promotion(policy)
      promo = policy["promotion"] || {}
      lines = ["## Promotion", ""]
      { "to test" => promo["to_test"], "to stable" => promo["to_stable"] }.each do |label, step|
        next unless step.is_a?(Hash)

        gates = Array(step["gates"]).map { |gate| gate["id"] }
        lines << "- #{label}: from `#{step['from']}`, by #{Array(step['actor']).join(' or ')}, gates #{gates.empty? ? 'none' : gates.join(', ')}"
      end
      stable = promo["to_stable"]
      if stable.is_a?(Hash) && Array(stable["actor"]) == ["operator"]
        lines << ""
        lines << "Only the operator runs `polispec promote #{policy['project']} --to stable`."
      end
      "#{lines.join("\n")}\n"
    end

    def operators(environments)
      lines = ["## Operators and rollback", ""]
      entries = ENV_NAMES.filter_map do |name|
        spec = environments["environments"][name]
        parts = []
        parts << "operators #{spec['operators'].join(', ')}" unless Array(spec["operators"]).empty?
        parts << "rollback `#{spec['rollback']}`" if spec["rollback"]
        parts.empty? ? nil : "- #{name}: #{parts.join('; ')}"
      end
      lines.concat(entries.empty? ? ["- none declared"] : entries)
      "#{lines.join("\n")}\n"
    end

    def data(environments)
      lines = ["## Data", ""]
      entries = ENV_NAMES.filter_map do |name|
        spec = environments["environments"][name]
        parts = []
        parts << "dirs #{spec.dig('data', 'dirs').join(', ')}" unless Array(spec.dig("data", "dirs")).empty?
        parts << "databases #{spec.dig('data', 'databases').join(', ')}" unless Array(spec.dig("data", "databases")).empty?
        parts << "secrets #{spec['secrets'].join(', ')}" unless Array(spec["secrets"]).empty?
        parts << "pii_spec #{spec['pii_spec']}" if spec["pii_spec"]
        parts.empty? ? nil : "- #{name}: #{parts.join('; ')}"
      end
      lines.concat(entries.empty? ? ["- none declared"] : entries)
      "#{lines.join("\n")}\n"
    end

    def upsert_row(text, row, project = nil)
      return "# AGENTS.md: #{project}\n\n#{row}\n" if text.nil?

      lines = text.lines
      index = lines.index { |line| line.start_with?("[ENVS]") }
      return lines.each_with_index.map { |line, i| i == index ? line_like(line, row) : line }.join if index

      index = lines.index { |line| ROW_PATTERN.match?(line) }
      return insert_at(lines, index, [line_like("\n", row), "\n"]) if index

      title = lines.index { |line| line.start_with?("# ") }
      return insert_after_title(lines, title, row) if title

      ["#{row}\n", "\n", *lines].join
    end

    def line_like(old, row)
      old.end_with?("\n") ? "#{row}\n" : row
    end

    def insert_at(lines, index, additions)
      lines.dup.insert(index, *additions).join
    end

    def insert_after_title(lines, title, row)
      position = title + 1
      additions = []
      if lines[position].nil?
        lines = lines.dup
        lines[title] = "#{lines[title].chomp}\n" unless lines[title].end_with?("\n")
        additions << "\n"
      elsif lines[position].strip.empty?
        position += 1
      else
        additions << "\n"
      end
      additions << (position >= lines.length ? row : "#{row}\n")
      additions << "\n" if position < lines.length
      insert_at(lines, position, additions)
    end

    def plan(root, rendered)
      agents_path = File.join(root, AGENTS_FILE)
      body_path = File.join(root, BODY_PATH)
      current_agents = File.file?(agents_path) ? File.read(agents_path) : nil
      current_body = File.file?(body_path) ? File.read(body_path) : nil
      next_agents = upsert_row(current_agents, rendered.row, rendered.project)
      [
        { path: body_path, content: rendered.body, changed: current_body != rendered.body },
        { path: agents_path, content: next_agents, changed: current_agents != next_agents }
      ]
    end

    def apply(file)
      return unless file[:changed]

      FileUtils.mkdir_p(File.dirname(file[:path]))
      mode = File.file?(file[:path]) ? File.stat(file[:path]).mode & 0o777 : 0o644
      temp = "#{file[:path]}.#{Process.pid}.tmp"
      File.write(temp, file[:content])
      File.chmod(mode, temp)
      File.rename(temp, file[:path])
    end

    def row_in(text)
      text.to_s.lines.find { |line| line.start_with?("[ENVS]") }&.chomp
    end

    def drift(repo, ref, project)
      repo = File.expand_path(repo)
      env_path = Environments.path_for(project.policy)
      return ["no #{Environments::FILE} at #{ref}; render needs it"] if Environments.git(repo, "rev-parse", "--verify", "--quiet", "#{ref}:#{env_path}").nil?

      rendered = render(source_from_ref(repo, ref, project.policy))
      details = []
      agents = Environments.git(repo, "show", "#{ref}:#{AGENTS_FILE}")
      current = row_in(agents)
      if current.nil?
        details << "AGENTS.md at #{ref} has no [ENVS] row"
      elsif current != rendered.row
        details << "the [ENVS] row at #{ref} differs from a fresh render"
      end
      body = Environments.git(repo, "show", "#{ref}:#{BODY_PATH}")
      if body.nil?
        details << "#{BODY_PATH} is missing at #{ref}"
      elsif body != rendered.body
        details << "#{BODY_PATH} at #{ref} differs from a fresh render"
      end
      details
    rescue Polispec::Error
      []
    end
  end
end
